default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: <%= ENV.fetch("DB_PASS") { } %>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
