default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: <%= ENV.fetch("DB_PASS") { } %>

development:
  <<: *default
  socket: /tmp/mysql.sock
  database: kakechi_development

test:
  <<: *default

production:
  <<: *default
  socket: /var/lib/mysql/mysql.sock
  database: kakechi_production
